# Generated by Django 4.2.4 on 2023-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField(max_length=50)),
                ('phoneNo', models.IntegerField(max_length=11)),
            ],
        ),
    ]
