# Generated by Django 4.2.4 on 2023-10-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.IntegerField(),
        ),
    ]
