# Generated by Django 4.2.4 on 2023-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_user_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('courtId', models.AutoField(default='', primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
