# Generated by Django 4.2.4 on 2023-10-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=100)),
                ('rate', models.IntegerField()),
                ('courtId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.court')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.user')),
            ],
        ),
    ]
