# Generated by Django 4.2.4 on 2023-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='courtId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.TextField(max_length=11),
        ),
    ]
