# Generated by Django 4.2.4 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_court_courtid_alter_user_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='userId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
