# Generated by Django 4.2.4 on 2023-10-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_id_alter_booking_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
